on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: init
        run: |
          sudo apt-get update
          sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot kmod cpio git python3-docutils gettext automake autopoint texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
      - name: build
        run: |
          mkdir /opt/bin
          git clone --depth=1 https://github.com/felix-fly/rt-n56u.git /opt/rt-n56u
          cd /opt/rt-n56u/toolchain-mipsel
          sh dl_toolchain.sh
          cd /opt/rt-n56u/trunk
          sed -i '$a\export SSL_CERT_FILE=/usr/lib/cacert.pem' user/scripts/profile
          sed -i 's/size_etc="6M"/size_etc="16M"/' user/scripts/dev_init.sh
          sed -i '/INCLUDE/{s/=y/=n/}' configs/templates/NEWIFI3.config
          sed -i '/LANG_CN/{s/=n/=y/}' configs/templates/NEWIFI3.config
          sed -i '/ENABLE_IPV6/{s/=n/=y/}' configs/templates/NEWIFI3.config
          sed -i '7c size_tmp="128M"' user/scripts/dev_init.sh    #调整/tmp分区为128MB
          sed -i '898,899d' user/rc/net.c                         #修复ios访问bug
          sed -i '/_OPENSS/{s/=n/=y/}' configs/templates/NEWIFI3.config
          sed -i '/HTTPS/{s/=n/=y/}' configs/templates/NEWIFI3.config
          sed -i '/IPSET/{s/=n/=y/}' configs/templates/NEWIFI3.config
          sed -i '/CURL/{s/=n/=y/}' configs/templates/NEWIFI3.config
          sed -i '/HTOP/{s/=n/=y/}' configs/templates/NEWIFI3.config
          echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y" >> configs/templates/NEWIFI3.config
          echo "CONFIG_FIRMWARE_INCLUDE_XRAY=y" >> configs/templates/NEWIFI3.config

          # NEWIFI3
          fakeroot ./build_firmware_modify NEWIFI3
          mv /opt/rt-n56u/trunk/images/*.trx /opt/bin/NEWIFI3.trx
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: /opt/bin
