on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: init
        run: |
          sudo apt-get update
          sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot kmod cpio git python3-docutils gettext automake autopoint texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
      - name: build
        run: |
          mkdir /opt/bin
          git clone --depth=1 https://github.com/felix-fly/rt-n56u.git /opt/rt-n56u
          cd /opt/rt-n56u/toolchain-mipsel
          sh dl_toolchain.sh
          cd /opt/rt-n56u/trunk
          
          # remove the dnsmasq cache size config
          sed -i 's/fprintf(fp, "cache-size=%d\\n", DNS_RELAY_CACHE_MAX);/\/\/fprintf(fp, "cache-size=%d\\n", DNS_RELAY_CACHE_MAX);/' user/rc/services_ex.c
          
          # build-in smartdns
          rm -rf user/smartdns
          mkdir -p user/smartdns
          wget -P user/smartdns/ https://raw.githubusercontent.com/felix-fly/v2ray-padavan-doh/master/padavan/smartdns/Makefile
          sed -i '$a\export SSL_CERT_FILE=/usr/lib/cacert.pem' user/scripts/profile
          # remove ui
          sed -i 's/found_app_smartdns = 1/found_app_smartdns = 0/' user/httpd/web_ex.c

          # build-in xray
          rm -rf user/xray
          mkdir -p user/xray
          wget -P user/xray/ https://raw.githubusercontent.com/felix-fly/v2ray-padavan-doh/master/padavan/xray/Makefile
          
          cp -f $GITHUB_WORKSPACE/asus_logo.png  user/www/n56u_ribbon_fixed/bootstrap/img/asus_logo.png   #替换logo
          cp -f $GITHUB_WORKSPACE/banner         user/scripts/banner
          sed -i '/2011-2019/{s/2019/2023/}' user/www/Makefile    #过年好
          sed -i '3c FIRMWARE_BUILDS_REV=lissom' versions.inc     #更新版本
          sed -i '7c size_tmp="128M"' user/scripts/dev_init.sh    #调整/tmp分区为128MB
          sed -i '898,899d' user/rc/net.c                         #修复ios访问bug
      
          sed -i '1c SRC_NAME=openssl-1.1.1w' libs/libssl/Makefile                #更新openssl
          mv libs/libssl/openssl-1.1.1k.patch libs/libssl/openssl-1.1.1w.patch
          sed -i 's/size_etc="6M"/size_etc="16M"/' user/scripts/dev_init.sh
         
          sed -i '/INCLUDE/{s/=y/=n/}' configs/templates/NEWIFI3.config
          sed -i '/LANG_CN/{s/=n/=y/}' configs/templates/NEWIFI3.config
          sed -i '/ENABLE_IPV6/{s/=n/=y/}' configs/templates/NEWIFI3.config

          sed -i '/_OPENSS/{s/=n/=y/}' configs/templates/NEWIFI3.config
          sed -i '/HTTPS/{s/=n/=y/}' configs/templates/NEWIFI3.config
          sed -i '/IPSET/{s/=n/=y/}' configs/templates/NEWIFI3.config
          sed -i '/CURL/{s/=n/=y/}' configs/templates/NEWIFI3.config
          sed -i '/HTOP/{s/=n/=y/}' configs/templates/NEWIFI3.config
          sed -i '/IPERF3/{s/=n/=y/}' configs/templates/NEWIFI3.config
          sed -i '/TTYD/{s/=n/=y/}' configs/templates/NEWIFI3.config
          echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y" >> configs/templates/NEWIFI3.config
          echo "CONFIG_FIRMWARE_INCLUDE_XRAY=y" >> configs/templates/NEWIFI3.config

          # NEWIFI3
          fakeroot ./build_firmware_modify NEWIFI3
          mv /opt/rt-n56u/trunk/images/*.trx /opt/bin/NEWIFI3.trx
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: NEWIFI3-smartdns-xray
          path: /opt/bin
