#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
name: Build Padavan for ZBT-WE1826

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Clone source code
      run: |
        git clone --depth=1 https://github.com/keke1023/Padavan.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
    - name: Build Firmware
      env:
        TNAME: OYE-001
      run: |
        cd /opt/rt-n56u/trunk
        sed -i '6c CONFIG_FIRMWARE_PRODUCT_ID="ZBT-WE1826"' configs/templates/$TNAME.config
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config not found "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        
        #######最小化系统及更新设置###################################################################
        cp -f $GITHUB_WORKSPACE/asus_logo.png  user/www/n56u_ribbon_fixed/bootstrap/img/asus_logo.png   #替换logo
        cp -f $GITHUB_WORKSPACE/banner         user/scripts/banner
        sed -i '/2011-2019/{s/2019/2024/}' user/www/Makefile    #过年好
        sed -i '2c FIRMWARE_BUILDS_VER=240701' versions.inc     #更新版本
        sed -i '3c FIRMWARE_BUILDS_REV=zbt-mod' versions.inc    #更新版本
        sed -i '/INCLUDE/{s/=y/=n/}' .config                    #关闭所有INCLUDE
        sed -i '/LANG_CN/{s/=n/=y/}' .config                    #设置默认语言为中文
        sed -i '7c size_tmp="32M"' user/scripts/dev_init.sh     #调整/tmp分区为32MB
        sed -i '898,899d' user/rc/net.c                         #修复ios访问bug
        
        #######修改WAN-LAN适配#######################################################################
        sed -i '1797c CONFIG_RAETH_ESW_PORT_WAN=4' configs/boards/OYE-001/kernel-3.4.x.config
        sed -i '1798c CONFIG_RAETH_ESW_PORT_LAN1=3' configs/boards/OYE-001/kernel-3.4.x.config
        sed -i '1799c CONFIG_RAETH_ESW_PORT_LAN2=2' configs/boards/OYE-001/kernel-3.4.x.config
        sed -i '1800c CONFIG_RAETH_ESW_PORT_LAN3=1' configs/boards/OYE-001/kernel-3.4.x.config
        sed -i '1801c CONFIG_RAETH_ESW_PORT_LAN4=0' configs/boards/OYE-001/kernel-3.4.x.config
        cp -f $GITHUB_WORKSPACE/ZBT.board.h  configs/boards/OYE-001/board.h
        ######更新软件源码###############################################################################
        sed -i '/htop-3.0.5/{s/3.0.5/3.0.2/}' user/htop/Makefile                #更新htop
        sed -i '1c SRC_NAME=openssl-1.1.1s' libs/libssl/Makefile                #更新openssl
        mv libs/libssl/openssl-1.1.1k.patch libs/libssl/openssl-1.1.1s.patch
        
        ######恢复基础工具###############################################################################
        sed -i '/_OPENSS/{s/=n/=y/}' .config
        sed -i '/IPSET/{s/=n/=y/}' .config
        sed -i '/CURL/{s/=n/=y/}' .config
        sed -i '/HTOP/{s/=n/=y/}' .config
        sed -i '/TTYD/{s/=n/=y/}' .config
        sed -i '/ttyd_enable/{s/0/1/}' user/shared/defaults.c
        
        ######默认扩展功能，注释以禁用####################################################################
        sed -i '/INCLUDE_HTTPS/{s/=n/=y/}' .config              #开启HTTPS
        sed -i '/INCLUDE_LPRD/{s/=n/=y/}' .config               #LPRD打印
        sed -i '/INCLUDE_U2EC/{s/=n/=y/}' .config               #打印相关
        sed -i '/INCLUDE_HDPARM/{s/=n/=y/}' .config             #开启HTTPS
        sed -i '/INCLUDE_PARTED/{s/=n/=y/}' .config             #LPRD打印
        sed -i '/FTP/{s/=n/=y/}' .config                        #FTP、SFTP文件访问
        sed -i '/INCLUDE_SMBD/{s/=n/=y/}' .config               #开启SAMBA
        sed -i '/INCLUDE_SMBD_SYSLOG/{s/=y/=n/}' .config        #关闭SAMBA日志
        echo "CONFIG_FIRMWARE_INCLUDE_SFE=y" >> .config         #添加SFE支持
        
        ########重新配置smartdns#########################################################################
        cp -f $GITHUB_WORKSPACE/smartdns/Makefile  user/smartdns/Makefile
        cp -f $GITHUB_WORKSPACE/smartdns/smartdns_custom.conf  user/smartdns/smartdns_custom.conf
        sed -i '4c <title><#Web_Title#> - <#menu5_24#></title>' user/www/n56u_ribbon_fixed/Advanced_smartdns.asp
        wget https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-smartdns.conf -O user/smartdns/ad.hosts
        echo "CONFIG_FIRMWARE_INCLUDE_SMARTDNS=y" >> .config            #smartdns
        sed -i '/sdns_enable/{s/0/1/}' user/shared/defaults.c
        
        ######开始打包####################################################################################
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/ZBT-WE1826.trx
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: ZBT-WE1826
        path: /opt/images
